name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Create deployment package
        run: zip -r app.zip . -x "*.git*"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      #########################################
      # Upload to S3
      #########################################

      - name: Upload to S3
        run: |
          aws s3 cp app.zip s3://week-3-lab-2/app-${{ github.sha }}.zip

      #########################################
      # Create Application Version
      #########################################

      - name: Create Elastic Beanstalk Version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name week3-node-app \
            --version-label ${{ github.sha }} \
            --source-bundle S3Bucket="week-3-lab-2",S3Key="app-${{ github.sha }}.zip"

      #########################################
      # Deploy Version
      #########################################

      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk update-environment \
            --environment-name week3-node-env \
            --version-label ${{ github.sha }}